apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "mssql-ssis.fullname" . }}
  labels:
    app: {{ template "mssql-ssis.name" . }}
    chart: {{ template "mssql-ssis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mssql-ssis.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "mssql-ssis.name" . }}
        release: {{ .Release.Name }}
      {{- if or .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      containers:
        - name: kafka-connect-ui
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          ports:
          - containerPort: {{ .Values.servicePort }}
          env:
          {{- range $key, $value := .Values.customEnv }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
