acceptEula:
  value: "y"
edition:
  value: Express
collation: SQL_Latin1_General_CP1_CI_AS
lcid: 1033
hadr: 0
# Override sapassword in templates/secret.yaml
sapassword: "MyStrongPassword1234"
image:
  repository: mcr.microsoft.com/mssql/ha
  tag: 2019-CTP2.1-ubuntu
  pullPolicy: IfNotPresent
  ## It is possible to specify docker registry credentials
  ## See https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  # pullSecrets:
  #    - name: regsecret

service:
  # If headless is set to TRUE then the service type is ignored
  headless: false
  type: ClusterIP
  port: 1433
  targetPort: 1433
  annotations: {}
deployment:
  annotations: {}
persistence:
  enabled: true
  # existingDataClaim:
  # existingTransactionLogClaim:
  # existingBackupClaim:
  # existingMasterClaim:
  storageClass: ""
  dataAccessMode: ReadWriteOnce
  dataSize: 1Gi
  transactionLogAccessMode: ReadWriteOnce
  transactionLogSize: 1Gi
  backupAccessMode: ReadWriteOnce
  backupSize: 1Gi
  masterAccessMode: ReadWriteOnce
  masterSize: 1Gi
livenessprobe:
  initialDelaySeconds: 15
  periodSeconds: 20
readinessprobe:
  initialDelaySeconds: 5
  periodSeconds: 10
resources:
  limits:
  #  cpu: 100m
    memory: 2Gi
  # requests:
  #  cpu: 100m
  #  memory: 2Gi
nodeSelector: {}
  # kubernetes.io/hostname: minikube

## ------------------------------------------------------
## MSSQL Client
## ------------------------------------------------------
mssqlcli:
  enabled: false
  image: mcr.microsoft.com/mssql-tools
  imageTag: latest


defaultDatabase:
  enabled: true
  name: kafka_connect_db
  user: sa
  password: MyStrongPassword1234
  host: v1-mssql-linux
