replicaCount: 1

image:
  repository: registry.digitalocean.com/bitflow-1/bitflow
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 50m
#     memory: 64Mi
