apiVersion: v1
kind: Secret
metadata:
  name: new-sql-secrets
  namespace: datalake
data:
  sapassword : {{ .Values.sapassword | b64enc | quote }}
  masterkeypassword : {{ .Values.sapassword | b64enc | quote }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-secrets
  namespace: datalake
data:
  sapassword : {{ .Values.sapassword | b64enc | quote }}
type: Opaque
